** log for folder 2
*** Sat Aug 29, 2015 14:17:19 having a folder named 2 is stupid.

    What I need to do here is use what's here to make something useful.  

    There are 2 useful things here.  A calculator is useful, but it's
    not as useful as the dynamic array which could be made into a
    library that can be built on.  

    So what I want to do is build dynamicArray.c into dynamicArray.so
    with gcc in the makefile.  Then build testDynArray.c and calc.c
    by linking to the .so file.  


    # add instructions and links to building shared / static libraries
    # with gcc here. 

    http://www.adp-gmbh.ch/cpp/gcc/create_lib.html
    
    Static libs are created with ar.

    Shared libs are created with 
    
    gcc -c -fPIC
    gcc -shared -Wl, -soname,

*** Sat Aug 29, 2015 14:25:46 benchmarking

    Eventually, I'm going to want to benchmark this stuff.  Where do I
    have benchmarking routines?

*** Mon Aug 31, 2015 07:33:14 not getting hung up
    
    Don't want to get too hung up on details, because there's a lot of
    other things to get to here, folder 2 is just the start.

    Still trying to analyze shared and static libraries as well as
    object code.  What's the big difference?   This is really all
    about implementation which fascinates me, but the project is more
    about abstraction than implementation.   So the key is not to get
    too hung up on implementation details.  

    If I wanted to thoroughly analyze things, then looking at them in
    hex mode is probably a good way.   I'll come back to that on a
    different pass, right now I just want to build the static and
    shared libraries.  

    I wanted to make the next folder build off the library in this
    folder.  Mostly to get a better grip on larger scale projects
    using gnu-make.    

    I'm fairly certain that I'm not going to be able to make this code
    base shippable by tomorrow.  

*** Mon Aug 31, 2015 07:38:38 looking ahead [[file:/n900t/usr/src/mlib/3/]]
*** Mon Aug 31, 2015 09:01:45 build notes
    This works on ubuntu, but not on cygwin. 

    http://stackoverflow.com/questions/16154130/cygwin-g-linker-doesnt-find-shared-library
